### ISSUE TITLE
Make app responsive

### ISSUE THREAD

**Issue by markus-walther** [axa-ch-webhub-cloud/inno-day-time-boii#1]
Double-check that the app adapts to mobile viewports. Document that it supports common viewport sizes.
Minimally support  portrait mode of typical smartphones, from 320px and above.
If issues are found, fix them. E.g. on 320px time entry fields only show the hour part.
Attach screenshots for documentation purposes in comments.

**Comment by raphaellueckl** [comment]
![image](https://user-images.githubusercontent.com/8248662/97276033-f86b1500-1836-11eb-98db-b73156d96d0e.png)

On 320px, minutes not readable.
