### ISSUE TITLE
Wrong "how much time to go home"

### ISSUE THREAD

**Issue by danyball** [axa-ch-webhub-cloud/inno-day-time-boii#32]
Click "KOMMEN". The time on the top right is wrong. 
see sshot:

![image](https://user-images.githubusercontent.com/7448004/105054003-d2d65c00-5a71-11eb-8668-957e92f3b5b2.png)

**Comment by markus-walther** [comment]
Now it is correct (time entered via Kommen, 8.4 hours required work):

![Screen Shot 2021-08-17 at 14 06 31](https://user-images.githubusercontent.com/46926507/129722780-437be517-a7cc-4e3a-8cd7-02f0a3ba6b34.png)

This was fixed as a side-effect of PR #38.
